<?php

return [
    'Fasilitas Fisik Dasar' => [
        ['id' => 'kursi_mahasiswa', 'text' => 'Kursi Mahasiswa', 'icon' => 'bx-chair'],
        ['id' => 'meja_mahasiswa', 'text' => 'Meja Mahasiswa', 'icon' => 'bx-table'],
        ['id' => 'meja_dosen', 'text' => 'Meja Dosen', 'icon' => 'bx-user-voice'],
        ['id' => 'podium', 'text' => 'Podium', 'icon' => 'bx-broadcast'],
        ['id' => 'whiteboard', 'text' => 'Whiteboard / Papan Tulis', 'icon' => 'bx-edit-alt'],
        ['id' => 'flipchart', 'text' => 'Flipchart', 'icon' => 'bx-notepad'],
        ['id' => 'lemari', 'text' => 'Lemari / Rak Buku', 'icon' => 'bx-book'],
        ['id' => 'ac', 'text' => 'AC / Kipas Angin', 'icon' => 'bx-cool'],
        ['id' => 'karpet', 'text' => 'Karpet / Lantai', 'icon' => 'bx-grid-alt'],
        ['id' => 'tirai', 'text' => 'Tirai / Gorden', 'icon' => 'bx-window'],
        ['id' => 'papan_pengumuman', 'text' => 'Papan Pengumuman', 'icon' => 'bx-pin'],
        ['id' => 'jam_dinding', 'text' => 'Jam Dinding', 'icon' => 'bx-time'],
        ['id' => 'tempat_sampah', 'text' => 'Tempat Sampah', 'icon' => 'bx-trash'],
    ],
    'Fasilitas Elektronik & Teknologi' => [
        ['id' => 'proyektor', 'text' => 'Proyektor', 'icon' => 'bx-video'],
        ['id' => 'layar_proyektor', 'text' => 'Layar Proyektor', 'icon' => 'bx-fullscreen'],
        ['id' => 'tv', 'text' => 'Smart TV', 'icon' => 'bx-tv'],
        ['id' => 'monitor', 'text' => 'LCD Monitor', 'icon' => 'bx-desktop'],
        ['id' => 'komputer_dosen', 'text' => 'Komputer Dosen', 'icon' => 'bx-laptop'],
        ['id' => 'komputer_mahasiswa', 'text' => 'Komputer Mahasiswa', 'icon' => 'bx-desktop'],
        ['id' => 'wifi', 'text' => 'Wi-Fi / LAN', 'icon' => 'bx-wifi'],
        ['id' => 'speaker', 'text' => 'Speaker / Sound System', 'icon' => 'bx-speaker'],
        ['id' => 'mikrofon', 'text' => 'Mikrofon', 'icon' => 'bx-microphone'],
        ['id' => 'cctv', 'text' => 'Kamera CCTV', 'icon' => 'bx-camera-home'],
        ['id' => 'conference', 'text' => 'Sistem Conference', 'icon' => 'bx-video-plus'],
        ['id' => 'switch', 'text' => 'Switch / Hub Jaringan', 'icon' => 'bx-network-chart'],
        ['id' => 'stopkontak', 'text' => 'Stopkontak Tambahan', 'icon' => 'bx-plug'],
        ['id' => 'charger', 'text' => 'Charging Station', 'icon' => 'bx-battery'],
    ],
    'Fasilitas Laboratorium' => [
        ['id' => 'alat_praktikum', 'text' => 'Alat Praktikum', 'icon' => 'bx-test-tube'],
        ['id' => 'pc_lab', 'text' => 'PC / Laptop Lab', 'icon' => 'bx-laptop'],
        ['id' => 'printer', 'text' => 'Printer / Scanner', 'icon' => 'bx-printer'],
        ['id' => 'printer_3d', 'text' => 'Mesin 3D Printer', 'icon' => 'bx-cube'],
        ['id' => 'alat_elektronika', 'text' => 'Alat Elektronika', 'icon' => 'bx-chip'],
        ['id' => 'alat_kimia', 'text' => 'Peralatan Kimia', 'icon' => 'bx-vial'],
        ['id' => 'rak_sampel', 'text' => 'Rak Sampel', 'icon' => 'bx-archive'],
        ['id' => 'meja_lab', 'text' => 'Meja Lab Tahan Kimia', 'icon' => 'bx-lock'],
    ],
    'Fasilitas Keamanan & Darurat' => [
        ['id' => 'apar', 'text' => 'APAR (Pemadam Api)', 'icon' => 'bxs-hot'],
        ['id' => 'alarm', 'text' => 'Alarm Darurat', 'icon' => 'bx-alarm-exclamation'],
        ['id' => 'p3k', 'text' => 'Kotak P3K', 'icon' => 'bx-first-aid'],
        ['id' => 'exit', 'text' => 'Exit Sign / Evakuasi', 'icon' => 'bx-log-out'],
        ['id' => 'detektor_asap', 'text' => 'Detektor Asap', 'icon' => 'bx-radar'],
    ],
    'Fasilitas Penunjang' => [
        ['id' => 'dispenser', 'text' => 'Dispenser / Galon', 'icon' => 'bx-droplet'],
        ['id' => 'ac_central', 'text' => 'AC Central', 'icon' => 'bx-cool'],
        ['id' => 'lampu_belajar', 'text' => 'Lampu Belajar', 'icon' => 'bx-bulb'],
        ['id' => 'kamera_sidang', 'text' => 'Kamera Ujian/Sidang', 'icon' => 'bx-camera'],
        ['id' => 'alat_tulis', 'text' => 'Alat Tulis', 'icon' => 'bx-pencil'],
        ['id' => 'kontrol_cahaya', 'text' => 'Panel Kontrol Cahaya', 'icon' => 'bx-slider'],
        ['id' => 'kontrol_suara', 'text' => 'Panel Kontrol Suara', 'icon' => 'bx-volume'],
    ],
    'Akses & Kontrol' => [
        ['id' => 'rfid', 'text' => 'Kartu Akses / RFID', 'icon' => 'bx-id-card'],
        ['id' => 'pintu_otomatis', 'text' => 'Pintu Otomatis', 'icon' => 'bx-door-open'],
        ['id' => 'reservasi_digital', 'text' => 'Reservasi Digital', 'icon' => 'bx-calendar'],
        ['id' => 'qr_scanner', 'text' => 'QR Code Scanner', 'icon' => 'bx-qr'],
        ['id' => 'sensor_gerak', 'text' => 'Sensor Gerak / Cahaya', 'icon' => 'bx-brightness'],
    ]
];
