<?php
// Variables
return [
    "creatorName" => "Manejemen Bisnis ITS",
    "creatorUrl" => "https://www.youtube.com/channel/UCzHCBGSt9TLaJ3zVxPZ0EPQ",
    "templateName" => "SIMBA",
    "templateSuffix" => "Bootstrap Dashboard FREE",
    "templateVersion" => "2.0.0",
    "templateFree" => true,
    "templateDescription" => "Sistem ini menyediakan layanan persuratan, peminjaman ruangan, dan peminjaman alat di Departemen Manajemen Bisnis ITS",
    "templateKeyword" => "Manajemen Bisnis ITS, ITS, Pengajuan Surat Manajemen Bisnis ITS, Pengajuan Ruangan Manajemen Bisnis ITS",
    "licenseUrl" => "https://themeselection.com/license/",
    "livePreview" => "https://demos.themeselection.com/sneat-bootstrap-html-laravel-admin-template-free/demo/",
    "productPage" => "https://themeselection.com/item/sneat-dashboard-free-laravel/",
    "productPagePro" => "https://themeselection.com/item/sneat-dashboard-pro-laravel/",
    "support" => "https://github.com/themeselection/sneat-html-laravel-admin-template-free/issues",
    "moreThemes" => "https://themeselection.com/",
    "documentation" => "https://demos.themeselection.com/sneat-bootstrap-html-admin-template/documentation",
    "repository" => "https://github.com/themeselection/sneat-bootstrap-html-laravel-admin-template-free",
    "gitRepo" => "https://github.com/themeselection/sneat-bootstrap-html-laravel-admin-template-free.git",
    "gitRepoAccess" => "https://tools.themeselection.com/github/github-access",
    "githubFreeUrl" => "https://github.com/themeselection",
    "facebookUrl" => "https://www.facebook.com/ThemeSelections/",
    "twitterUrl" => "https://twitter.com/Theme_Selection",
    "githubUrl" => "https://github.com/themeselection",
    "dribbbleUrl" => "https://dribbble.com/themeselection",
    "instagramUrl" => "https://www.instagram.com/themeselection/",
    "namaLayananPersuratan" => "Surat",
    "namaLayananSewaRuangan" => "Ruangan",
    "namaLayananSewaPeralatan" => "Peralatan",
    "namaFakultas" => "MANAJEMEN BISNIS ITS",
];
